# test_dogrib
"""
Before you run this, run
python main.py --input-instance-folder ../data/dogrib/ --output-folder ../results/dogrib/ --ignitions --sim-years 1 --nsims 1 --finalGrid --weather rows --nweathers 1 --Fire-Period-Length 1.0 --output-messages --ROS-CV 0.0 --seed 123 --stats --allPlots --IgnitionRad 5 --grids --combine
That will create the input files. Then we run basically the same command under the tester, but
with --onlyProcessing to avoid calling the compiled C++ code.
# TBD: this test module should take the command line as an arg, so it does not have to
#      be pasted into the github action yml file and here. It should just be in the action
#      yml file and read here, with --onlyProcessing appended here.
"""
import  unittest
import os.path
import datetime
from cell2fire.utils.ParseInputs import make_parser
from cell2fire.Cell2FireC_class import *
import cell2fire  # for path finding
import os
from PIL import Image, ImageChops
import collections


p = str(cell2fire.__path__)
l = p.find("'")
r = p.find("'", l+1)
cell2fire_path = p[l+1:r]
data_path = os.path.join(cell2fire_path, "..","data")

# Those files are checked in the test
result_Forest08 = os.path.join(cell2fire_path, "..", "results", "dogrib", "Grids", "Grids1", "ForestGrid08.csv")
baseline_Forest08 = os.path.join(cell2fire_path, "..", "tests", "baseline", "dogrib", "ForestGrid08.csv")
result_Fire09 = os.path.join(cell2fire_path, "..", "results", "dogrib", "Plots", "Plots1", "Fire09.png")
baseline_Fire09 = os.path.join(cell2fire_path, "..", "tests", "baseline", "dogrib", "Fire09.png")
result_Propagation = os.path.join(cell2fire_path, "..", "results", "dogrib", "Plots", "Plots1", "PropagationTree1.png")
baseline_Propagation = os.path.join(cell2fire_path, "..", "tests", "baseline", "dogrib", "PropagationTree1.png")

def _cmd_list():
    datadir = os.path.abspath(os.path.join(data_path, "dogrib"))
    resultsdir = os.path.abspath(os.path.join(data_path, "..", "results", "dogrib"))
    ### python main.py --input-instance-folder ../data/dogrib/ --output-folder ../results/dogrib --ignitions --sim-years 1 --nsims 1 --finalGrid --weather rows --nweathers 1 --Fire-Period-Length 1.0 --output-messages --ROS-CV 0.0 --seed 123 --stats --allPlots --IgnitionRad 5 --grids --combine
    baselist = ["--input-instance-folder", datadir,
                "--output-folder", resultsdir,
                "--ignitions",
                "--sim-years", "1",
                "--nsims",  "1",
                "--finalGrid",
                "--weather", "rows",
                "--nweathers", "1",
                "--Fire-Period-Length", "1.0",
                "--output-messages",
                "--ROS-CV", "0.0",
                "--seed", "123",
                "--stats",
                "--allPlots",
                "--IgnitionRad", "5",
                "--grids",
                "--combine"]
    return baselist
    

class TestMain(unittest.TestCase):

    @classmethod
    def setUpClass(self):
        pass

    def test_readme_cmd(self):
        print("Running ", str(self.id()).split('.')[2])
        parser = make_parser()
        cmdlist = _cmd_list()
        cmdlist.append("--onlyProcessing")
        # only-processing means something else has to make the data!!! (no call to C++)

        args = parser.parse_args(cmdlist)
        env = Cell2FireC(args)  # see main.py
        env.stats()
        
        # Check if the result generated by the run matches the baseline files
        equal = True
        with open(result_Forest08) as result_file:
                with open(baseline_Forest08) as baseline_file:
                        for line1, line2 in zip(result_file, baseline_file):
                                                if not line1 == line2:
                                                        equal = False
                                                        print("In File Grids1/ForestGrid08.csv the result is wrong")

        imgfire1 = Image.open(result_Fire09)
        imgfire2 = Image.open(baseline_Fire09)
        imgprop1 = Image.open(result_Propagation)
        imgprop2 = Image.open(baseline_Propagation)
        diffFire = ImageChops.difference(imgfire1, imgfire2)
        diffProp = ImageChops.difference(imgprop1, imgprop2)
        """
        TBD: xxxx restore these two tests
        if diffFire.getbbox():
                equal = False 
                print("The image Fire09.png doesn't match the baseline file")                                                
        
        if diffProp.getbbox():
                equal = False 
                print("The image PropagationTree1.png doesn't match the baseline file")  
        
        self.assertTrue(equal)
        """

if __name__ == "__main__":

    """
    # first: full run to create data files for testing  
    Unfortunately, we can run't under os.system because the call to compiled code fails....
    cmdstr = "python main.py "
    for es in _readme_list():
        cmdstr += es+' '
    print("cmdstr=",cmdstr)
    os.system(cmdstr)
    """
    # something else needs to create the files
    # second: do the tests
    unittest.main()
