name: sub20x20  # Test2_zonghan
# dropped the Docker container use (DLW April 2025)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
    run:
        shell: bash -l {0}

jobs:
  build:
    name: sub20x20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.12
          auto-activate-base: false

      - name: make C++
        run: |
          cd cell2fire/Cell2FireC
          make
      - name: install dependencies
        run: |
	  pip install -r requirements.txt
      - name: setup the program
        run: |
          pip install -e .
  
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: create input data
        run: |
           cd cell2fire
           python main.py --input-instance-folder ../data/Sub20x20/ --output-folder ../results/Sub20x20 --ignitions --sim-years 1 --nsims 5 --finalGrid --weather rows --nweathers 1 --Fire-Period-Length 1.0 --output-messages --ROS-CV 0.0 --seed 123 --stats --allPlots --IgnitionRad 5 --grids --combine

      - name: run tests
        run: |
          cd tests
          pytest test_20x20.py --cov=../cell2fire --cov=./ --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./tests/coverage.xml
          flags: unittests
          ###env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false

