name: randweather
# dropped the Docker container use (DLW April 2025)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: random weather
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: 3.12
          auto-activate-base: false

      - name: Install Boost
        run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
      - name: Install Eigen
        run: sudo apt-get update && sudo apt-get install -y libeigen3-dev

      - name: make C++
        run: |
          cd cell2fire/Cell2FireC
          make
      - name: install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
      - name: setup the program
        run: |
          pip install -e .
    
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: create input data
        run: |
           cd cell2fire
           python main.py --input-instance-folder ../data/Harvest40x40/ --output-folder ../Harvest40x40 --ignitions --sim-years 2 --nsims 5 --grids --finalGrid --weather random --nweathers 200 --Fire-Period-Length 1.0 --output-messages --ROS-CV 0.8 --seed 123 --stats --allPlots --IgnitionRad 1 --combine --HarvestedCells ../data/Harvest40x40/band1_2.csv
      - name: Install pytest
        run: pip install pytest
      - name: run tests
        run: |
          cd tests
          pytest test_randweather.py 


